"""Project-maintained standard implementations built on top of trader core."""

from .indicators import (
    BollingerBandsIndicator,
    BollingerBandValue,
    EmaIndicator,
    HistoricalVolatilityIndicator,
    MacdIndicator,
    MacdValue,
    RollingVolatilityIndicator,
    RsiIndicator,
    SmaIndicator,
    ZScoreIndicator,
)
from .risk import (
    HaltRiskManager,
    MaxGrossExposureRiskManager,
    MaxOrdersPerRunRiskManager,
    MaxPositionUsdPerSymbolRiskManager,
    NoOpRiskManager,
    OpenBuyOrderLimitRiskManager,
)
from .signal_generators import InMemoryBarsSignalGenerator, SimpleBarsSignalGenerator
from .signals import (
    BollingerBandSignal,
    BollingerBwmaActionSignal,
    EmaCrossoverSignal,
    MacdCrossoverSignal,
    RsiThresholdSignal,
    SmaCrossoverSignal,
    SmaStretchSignal,
)
from .strategies import (
    CompositeStopPolicy,
    EntryPolicy,
    ExitPolicy,
    FixedStopLossPolicy,
    LongFlatSignalStrategy,
    NoOpStopPolicy,
    NoOpStrategy,
    RandomStrategy,
    SignalThresholdEntryPolicy,
    SignalThresholdExitPolicy,
    SimpleStrategy,
    StopPolicy,
    StrategySnapshot,
    ToggleUnitStrategy,
    TrailingStopPolicy,
    build_bollinger_band_strategy,
    build_mean_reversion_strategy,
    build_trend_following_strategy,
)

__all__ = [
    "SmaIndicator",
    "EmaIndicator",
    "HistoricalVolatilityIndicator",
    "RsiIndicator",
    "MacdIndicator",
    "MacdValue",
    "BollingerBandsIndicator",
    "BollingerBandValue",
    "RollingVolatilityIndicator",
    "ZScoreIndicator",
    "SmaCrossoverSignal",
    "EmaCrossoverSignal",
    "RsiThresholdSignal",
    "MacdCrossoverSignal",
    "SmaStretchSignal",
    "BollingerBandSignal",
    "BollingerBwmaActionSignal",
    "SimpleBarsSignalGenerator",
    "InMemoryBarsSignalGenerator",
    "NoOpRiskManager",
    "HaltRiskManager",
    "MaxOrdersPerRunRiskManager",
    "MaxGrossExposureRiskManager",
    "MaxPositionUsdPerSymbolRiskManager",
    "OpenBuyOrderLimitRiskManager",
    "NoOpStrategy",
    "SimpleStrategy",
    "RandomStrategy",
    "ToggleUnitStrategy",
    "StrategySnapshot",
    "EntryPolicy",
    "ExitPolicy",
    "StopPolicy",
    "NoOpStopPolicy",
    "FixedStopLossPolicy",
    "TrailingStopPolicy",
    "CompositeStopPolicy",
    "SignalThresholdEntryPolicy",
    "SignalThresholdExitPolicy",
    "LongFlatSignalStrategy",
    "build_trend_following_strategy",
    "build_mean_reversion_strategy",
    "build_bollinger_band_strategy",
]
