"""Model-backed research coordination over role-scoped Trader MCP tools.

The package owns model programs, public contracts, deterministic runtime
policy, LangGraph wiring, and operational checkpointing. It does not own
research evidence, deterministic domain services, or live-trading authority.
"""

from .mcp.catalogue import ToolCatalogue, ToolDefinition, first_slice_tool_catalogue
from .checkpointing import (
    CHECKPOINT_DSN_ENV,
    AgentCheckpointState,
    CheckpointConfigurationError,
    SpecialistCheckpointState,
    agent_checkpoint_digest,
    agent_public_state,
    build_agent_checkpoint_state,
    build_specialist_checkpoint_state,
    checkpoint_safe_observation,
    checkpoint_step,
    checkpoint_dsn_from_env,
    checkpoint_runtime_summary,
    coordinator_thread_config,
    open_postgres_checkpointer,
    specialist_thread_config,
    specialist_checkpoint_digest,
    validate_agent_checkpoint_state,
    validate_specialist_checkpoint_state,
)
from .contracts.domain import (
    AgentPhase,
    AgentRole,
    AgenticSliceResult,
    AgendaTaskProposal,
    BudgetUsage,
    CanonicalEvidenceRef,
    CompositeDataScope,
    CoordinatorAction,
    CoordinatorAgenda,
    CoordinatorDecision,
    DataAgentTurn,
    DataInputRole,
    DataScopeItem,
    ParameterContract,
    OperatorInterrupt,
    OperatorCancellation,
    OperatorResponse,
    PublicIssue,
    SpecialistDelegation,
    SpecialistConclusion,
    SpecialistReturn,
    SpecialistStatus,
    StrategyBuildContract,
    StrategyAgentTurn,
    ToolCallProposal,
    ToolObservation,
    build_delegation,
    build_specialist_return,
)
from .coordination.coordinator import ResearchCoordinator
from .model_runtime.client import (
    LlmClient,
    LlmConfigurationError,
    LlmJsonCompletion,
    LlmRequestError,
    LlmTokenUsage,
    RuntimeConfiguredLlmClient,
    StaticJsonLlmClient,
    UsageAwareLlmClient,
)
from .contracts.inputs import (
    SessionInputError,
    composite_data_scope_from_session,
    strategy_build_contract_from_session,
    validate_runtime_pins,
)
from .specialists.data_research import DataResearchAgent
from .mcp.runtime import McpExecutionResult, RoleScopedMcpRuntime
from .observability.events import (
    OBSERVABILITY_SCHEMA_VERSION,
    AgentErrorCategory,
    AgentEventAuthority,
    AgentEventCorrelation,
    AgentEventError,
    AgentEventLevel,
    AgentEventName,
    AgentObservabilityEvent,
    NoOpObservabilityEventSink,
    ObservabilityEventSink,
    ProjectionDetail,
    RecordingObservabilityEventSink,
    build_agent_observability_event,
    validate_agent_event_stream,
    validate_observability_fields,
)
from .observability.console import (
    AGENT_LOG_FORMAT_ENV,
    AGENT_LOG_LEVEL_ENV,
    AgentConsoleConfig,
    CompositeObservabilityEventSink,
    ConsoleLogFormat,
    ConsoleObservabilityEventSink,
    agent_console_config,
)
from .observability.emitter import AgentEventEmitter, EventClock
from .observability.projections import (
    project_agent_turn,
    project_budget_usage,
    project_checkpoint,
    project_coordinator_agenda,
    project_coordinator_decision,
    project_policy_result,
    project_specialist_return,
    project_terminal_result,
    project_tool_call_proposal,
    project_tool_observation,
)
from .mcp.policy import (
    AuthorizedToolCall,
    BudgetLedger,
    PolicyContext,
    PolicyViolation,
    ToolPolicy,
)
from .model_runtime.profiles import (
    AgentProgram,
    AgentProgramRegistry,
    ModelProfile,
    ModelProfileRegistry,
    development_model_profiles,
    profile_environment,
)
from .model_runtime.programs import first_slice_programs
from .coordination.scheduler import (
    BudgetReservation,
    ScheduledTask,
    SchedulingError,
    compute_ready_set,
)
from .application.runtime import (
    AgentRunOutcome,
    AgenticResearchRuntime,
    runtime_from_environment,
    runtime_manifest,
)
from .model_runtime.structured import (
    ModelInvocationResult,
    StructuredModelRunner,
    StructuredOutputError,
)
from .specialists.strategy_engineering import StrategyEngineeringAgent
from .mcp.client import (
    McpToolClient,
    McpToolDescription,
    PersistentStdioMcpToolClient,
    StdioMcpToolClient,
)
from .observability.tracing import (
    MlflowTraceSink,
    NoOpTraceSink,
    RecordingTraceSink,
    TraceCorrelation,
    TraceSink,
)

__all__ = [
    "CHECKPOINT_DSN_ENV",
    "AgentCheckpointState",
    "AgentConsoleConfig",
    "AgentErrorCategory",
    "AgentEventAuthority",
    "AgentEventCorrelation",
    "AgentEventError",
    "AgentEventLevel",
    "AgentEventName",
    "AgentEventEmitter",
    "AgentPhase",
    "AgentProgram",
    "AgentProgramRegistry",
    "AgentRole",
    "AgentRunOutcome",
    "AgenticResearchRuntime",
    "AgenticSliceResult",
    "AgentObservabilityEvent",
    "AgendaTaskProposal",
    "AuthorizedToolCall",
    "BudgetLedger",
    "BudgetReservation",
    "BudgetUsage",
    "CanonicalEvidenceRef",
    "CheckpointConfigurationError",
    "CompositeDataScope",
    "CompositeObservabilityEventSink",
    "ConsoleLogFormat",
    "ConsoleObservabilityEventSink",
    "CoordinatorAction",
    "CoordinatorAgenda",
    "CoordinatorDecision",
    "DataAgentTurn",
    "DataInputRole",
    "DataResearchAgent",
    "DataScopeItem",
    "EventClock",
    "LlmClient",
    "LlmConfigurationError",
    "LlmJsonCompletion",
    "LlmRequestError",
    "LlmTokenUsage",
    "McpExecutionResult",
    "McpToolClient",
    "McpToolDescription",
    "MlflowTraceSink",
    "ModelInvocationResult",
    "ModelProfile",
    "ModelProfileRegistry",
    "NoOpTraceSink",
    "NoOpObservabilityEventSink",
    "OBSERVABILITY_SCHEMA_VERSION",
    "AGENT_LOG_FORMAT_ENV",
    "AGENT_LOG_LEVEL_ENV",
    "OperatorInterrupt",
    "OperatorCancellation",
    "OperatorResponse",
    "ObservabilityEventSink",
    "ParameterContract",
    "PersistentStdioMcpToolClient",
    "PolicyContext",
    "PolicyViolation",
    "PublicIssue",
    "ProjectionDetail",
    "RecordingObservabilityEventSink",
    "RecordingTraceSink",
    "ResearchCoordinator",
    "RoleScopedMcpRuntime",
    "RuntimeConfiguredLlmClient",
    "ScheduledTask",
    "SchedulingError",
    "SessionInputError",
    "SpecialistDelegation",
    "SpecialistCheckpointState",
    "SpecialistConclusion",
    "SpecialistReturn",
    "SpecialistStatus",
    "StaticJsonLlmClient",
    "StdioMcpToolClient",
    "StrategyBuildContract",
    "StrategyEngineeringAgent",
    "StrategyAgentTurn",
    "StructuredModelRunner",
    "StructuredOutputError",
    "ToolCallProposal",
    "ToolCatalogue",
    "ToolDefinition",
    "ToolObservation",
    "ToolPolicy",
    "TraceCorrelation",
    "TraceSink",
    "UsageAwareLlmClient",
    "agent_checkpoint_digest",
    "agent_console_config",
    "agent_public_state",
    "build_agent_checkpoint_state",
    "build_agent_observability_event",
    "build_specialist_checkpoint_state",
    "build_delegation",
    "build_specialist_return",
    "checkpoint_dsn_from_env",
    "checkpoint_runtime_summary",
    "checkpoint_safe_observation",
    "checkpoint_step",
    "composite_data_scope_from_session",
    "compute_ready_set",
    "coordinator_thread_config",
    "development_model_profiles",
    "first_slice_programs",
    "first_slice_tool_catalogue",
    "open_postgres_checkpointer",
    "profile_environment",
    "project_agent_turn",
    "project_budget_usage",
    "project_checkpoint",
    "project_coordinator_agenda",
    "project_coordinator_decision",
    "project_policy_result",
    "project_specialist_return",
    "project_terminal_result",
    "project_tool_call_proposal",
    "project_tool_observation",
    "runtime_from_environment",
    "runtime_manifest",
    "specialist_thread_config",
    "specialist_checkpoint_digest",
    "validate_agent_event_stream",
    "validate_observability_fields",
    "strategy_build_contract_from_session",
    "validate_runtime_pins",
    "validate_agent_checkpoint_state",
    "validate_specialist_checkpoint_state",
]
