"""Model-backed research coordination over role-scoped Trader MCP tools.

The package owns model programs, public contracts, deterministic runtime
policy, LangGraph wiring, and operational checkpointing. It does not own
research evidence, deterministic domain services, or live-trading authority.
"""

from .catalogue import ToolCatalogue, ToolDefinition, first_slice_tool_catalogue
from .checkpointing import (
    CHECKPOINT_DSN_ENV,
    AgentCheckpointState,
    CheckpointConfigurationError,
    SpecialistCheckpointState,
    agent_checkpoint_digest,
    agent_public_state,
    build_agent_checkpoint_state,
    build_specialist_checkpoint_state,
    checkpoint_safe_observation,
    checkpoint_step,
    checkpoint_dsn_from_env,
    checkpoint_runtime_summary,
    coordinator_thread_config,
    open_postgres_checkpointer,
    specialist_thread_config,
    specialist_checkpoint_digest,
    validate_agent_checkpoint_state,
    validate_specialist_checkpoint_state,
)
from .contracts import (
    AgentPhase,
    AgentRole,
    AgenticSliceResult,
    AgendaTaskProposal,
    BudgetUsage,
    CanonicalEvidenceRef,
    CompositeDataScope,
    CoordinatorAction,
    CoordinatorAgenda,
    CoordinatorDecision,
    DataAgentTurn,
    DataInputRole,
    DataScopeItem,
    ParameterContract,
    OperatorInterrupt,
    OperatorCancellation,
    OperatorResponse,
    PublicIssue,
    SpecialistDelegation,
    SpecialistConclusion,
    SpecialistReturn,
    SpecialistStatus,
    StrategyBuildContract,
    StrategyAgentTurn,
    ToolCallProposal,
    ToolObservation,
    build_delegation,
    build_specialist_return,
)
from .coordinator import ResearchCoordinator
from .llm_client import (
    LlmClient,
    LlmConfigurationError,
    LlmJsonCompletion,
    LlmRequestError,
    LlmTokenUsage,
    RuntimeConfiguredLlmClient,
    StaticJsonLlmClient,
    UsageAwareLlmClient,
)
from .inputs import (
    SessionInputError,
    composite_data_scope_from_session,
    strategy_build_contract_from_session,
    validate_runtime_pins,
)
from .data_research import DataResearchAgent
from .mcp_runtime import McpExecutionResult, RoleScopedMcpRuntime
from .policy import (
    AuthorizedToolCall,
    BudgetLedger,
    PolicyContext,
    PolicyViolation,
    ToolPolicy,
)
from .profiles import (
    AgentProgram,
    AgentProgramRegistry,
    ModelProfile,
    ModelProfileRegistry,
    development_model_profiles,
    profile_environment,
)
from .programs import first_slice_programs
from .scheduler import (
    BudgetReservation,
    ScheduledTask,
    SchedulingError,
    compute_ready_set,
)
from .runtime import (
    AgentRunOutcome,
    AgenticResearchRuntime,
    runtime_from_environment,
    runtime_manifest,
)
from .structured_model import (
    ModelInvocationResult,
    StructuredModelRunner,
    StructuredOutputError,
)
from .strategy_engineering import StrategyEngineeringAgent
from .tool_client import (
    McpToolClient,
    McpToolDescription,
    PersistentStdioMcpToolClient,
    StdioMcpToolClient,
)
from .tracing import (
    MlflowTraceSink,
    NoOpTraceSink,
    RecordingTraceSink,
    TraceCorrelation,
    TraceSink,
)

__all__ = [
    "CHECKPOINT_DSN_ENV",
    "AgentCheckpointState",
    "AgentPhase",
    "AgentProgram",
    "AgentProgramRegistry",
    "AgentRole",
    "AgentRunOutcome",
    "AgenticResearchRuntime",
    "AgenticSliceResult",
    "AgendaTaskProposal",
    "AuthorizedToolCall",
    "BudgetLedger",
    "BudgetReservation",
    "BudgetUsage",
    "CanonicalEvidenceRef",
    "CheckpointConfigurationError",
    "CompositeDataScope",
    "CoordinatorAction",
    "CoordinatorAgenda",
    "CoordinatorDecision",
    "DataAgentTurn",
    "DataInputRole",
    "DataResearchAgent",
    "DataScopeItem",
    "LlmClient",
    "LlmConfigurationError",
    "LlmJsonCompletion",
    "LlmRequestError",
    "LlmTokenUsage",
    "McpExecutionResult",
    "McpToolClient",
    "McpToolDescription",
    "MlflowTraceSink",
    "ModelInvocationResult",
    "ModelProfile",
    "ModelProfileRegistry",
    "NoOpTraceSink",
    "OperatorInterrupt",
    "OperatorCancellation",
    "OperatorResponse",
    "ParameterContract",
    "PersistentStdioMcpToolClient",
    "PolicyContext",
    "PolicyViolation",
    "PublicIssue",
    "RecordingTraceSink",
    "ResearchCoordinator",
    "RoleScopedMcpRuntime",
    "RuntimeConfiguredLlmClient",
    "ScheduledTask",
    "SchedulingError",
    "SessionInputError",
    "SpecialistDelegation",
    "SpecialistCheckpointState",
    "SpecialistConclusion",
    "SpecialistReturn",
    "SpecialistStatus",
    "StaticJsonLlmClient",
    "StdioMcpToolClient",
    "StrategyBuildContract",
    "StrategyEngineeringAgent",
    "StrategyAgentTurn",
    "StructuredModelRunner",
    "StructuredOutputError",
    "ToolCallProposal",
    "ToolCatalogue",
    "ToolDefinition",
    "ToolObservation",
    "ToolPolicy",
    "TraceCorrelation",
    "TraceSink",
    "UsageAwareLlmClient",
    "agent_checkpoint_digest",
    "agent_public_state",
    "build_agent_checkpoint_state",
    "build_specialist_checkpoint_state",
    "build_delegation",
    "build_specialist_return",
    "checkpoint_dsn_from_env",
    "checkpoint_runtime_summary",
    "checkpoint_safe_observation",
    "checkpoint_step",
    "composite_data_scope_from_session",
    "compute_ready_set",
    "coordinator_thread_config",
    "development_model_profiles",
    "first_slice_programs",
    "first_slice_tool_catalogue",
    "open_postgres_checkpointer",
    "profile_environment",
    "runtime_from_environment",
    "runtime_manifest",
    "specialist_thread_config",
    "specialist_checkpoint_digest",
    "strategy_build_contract_from_session",
    "validate_runtime_pins",
    "validate_agent_checkpoint_state",
    "validate_specialist_checkpoint_state",
]
