"""Expose bounded orchestration contracts and deterministic persistence services.

The facade includes objectives, structured design requests, immutable protocol
proposals, approved protocols, capability snapshots, workflow DAGs, approvals,
results, terminal outcomes, and the services that persist their canonical
records. It deliberately omits MCP transport, checkpoint storage, agent policy,
and specialist implementations.
"""

from .enums import (
    ApprovalStatus,
    ArtifactCardinality,
    ArtifactSlotStatus,
    CapabilitySideEffect,
    DatasetRole,
    ExperimentProtocolStatus,
    OptimizationDirection,
    PrerequisiteKind,
    PrerequisiteStatus,
    ResearchObjectiveStatus,
    RetryDisposition,
    TunableValueType,
    WorkflowPlanStatus,
    WorkflowOutcomeStatus,
    WorkflowStepStatus,
)
from .protocols import (
    Approval,
    CostAssumption,
    ExperimentProtocol,
    InitialPortfolio,
    InitialPosition,
    MaterialAssumption,
    ObjectiveConstraint,
    OptimizationProtocol,
    ProtocolConstraint,
    ProtocolDataset,
    ProtocolRiskManager,
    ProtocolStrategy,
    ResearchObjective,
    RobustnessRequirement,
    TunableDimension,
)
from .proposals import (
    ExperimentDesignRequest,
    ExperimentProtocolProposal,
    apply_experiment_protocol_approvals,
    build_experiment_protocol_proposal,
    experiment_design_input_refs,
    experiment_protocol_design_digest,
    replace_experiment_design_refs,
)
from .workflows import (
    ArtifactSlot,
    CapabilityDefinition,
    Prerequisite,
    WorkflowPlan,
    WorkflowOutcome,
    WorkflowStep,
    WorkflowStepResult,
)
from .services import (
    RESEARCH_CREATE_EXPERIMENT_PROTOCOL_PROPOSAL,
    RESEARCH_RECORD_WORKFLOW_OUTCOME,
    RESEARCH_REGISTER_EXPERIMENT_WORKFLOW,
    create_experiment_protocol_proposal,
    record_workflow_outcome,
    register_experiment_workflow,
)

__all__ = [
    "Approval",
    "ApprovalStatus",
    "ArtifactCardinality",
    "ArtifactSlot",
    "ArtifactSlotStatus",
    "CapabilityDefinition",
    "CapabilitySideEffect",
    "CostAssumption",
    "DatasetRole",
    "ExperimentDesignRequest",
    "ExperimentProtocol",
    "ExperimentProtocolProposal",
    "ExperimentProtocolStatus",
    "InitialPortfolio",
    "InitialPosition",
    "MaterialAssumption",
    "ObjectiveConstraint",
    "OptimizationDirection",
    "OptimizationProtocol",
    "Prerequisite",
    "PrerequisiteKind",
    "PrerequisiteStatus",
    "ProtocolConstraint",
    "ProtocolDataset",
    "ProtocolRiskManager",
    "ProtocolStrategy",
    "ResearchObjective",
    "ResearchObjectiveStatus",
    "RetryDisposition",
    "RobustnessRequirement",
    "TunableDimension",
    "TunableValueType",
    "WorkflowPlan",
    "WorkflowOutcome",
    "WorkflowOutcomeStatus",
    "WorkflowPlanStatus",
    "WorkflowStep",
    "WorkflowStepResult",
    "WorkflowStepStatus",
    "RESEARCH_CREATE_EXPERIMENT_PROTOCOL_PROPOSAL",
    "RESEARCH_RECORD_WORKFLOW_OUTCOME",
    "RESEARCH_REGISTER_EXPERIMENT_WORKFLOW",
    "apply_experiment_protocol_approvals",
    "build_experiment_protocol_proposal",
    "create_experiment_protocol_proposal",
    "experiment_design_input_refs",
    "experiment_protocol_design_digest",
    "record_workflow_outcome",
    "replace_experiment_design_refs",
    "register_experiment_workflow",
]
