"""Expose provider-neutral contracts for bounded research orchestration.

The facade includes objectives, approved protocols, capability snapshots,
workflow DAGs, approvals, results, and terminal outcomes. It deliberately omits
tool execution, checkpoint storage, agent policy, and specialist implementations.
"""

from .enums import (
    ApprovalStatus,
    ArtifactCardinality,
    ArtifactSlotStatus,
    CapabilitySideEffect,
    DatasetRole,
    ExperimentProtocolStatus,
    OptimizationDirection,
    PrerequisiteKind,
    PrerequisiteStatus,
    ResearchObjectiveStatus,
    RetryDisposition,
    TunableValueType,
    WorkflowPlanStatus,
    WorkflowOutcomeStatus,
    WorkflowStepStatus,
)
from .protocols import (
    Approval,
    CostAssumption,
    ExperimentProtocol,
    InitialPortfolio,
    InitialPosition,
    MaterialAssumption,
    ObjectiveConstraint,
    OptimizationProtocol,
    ProtocolConstraint,
    ProtocolDataset,
    ProtocolRiskManager,
    ProtocolStrategy,
    ResearchObjective,
    RobustnessRequirement,
    TunableDimension,
)
from .workflows import (
    ArtifactSlot,
    CapabilityDefinition,
    Prerequisite,
    WorkflowPlan,
    WorkflowOutcome,
    WorkflowStep,
    WorkflowStepResult,
)
from .services import (
    RESEARCH_RECORD_WORKFLOW_OUTCOME,
    RESEARCH_REGISTER_EXPERIMENT_WORKFLOW,
    record_workflow_outcome,
    register_experiment_workflow,
)

__all__ = [
    "Approval",
    "ApprovalStatus",
    "ArtifactCardinality",
    "ArtifactSlot",
    "ArtifactSlotStatus",
    "CapabilityDefinition",
    "CapabilitySideEffect",
    "CostAssumption",
    "DatasetRole",
    "ExperimentProtocol",
    "ExperimentProtocolStatus",
    "InitialPortfolio",
    "InitialPosition",
    "MaterialAssumption",
    "ObjectiveConstraint",
    "OptimizationDirection",
    "OptimizationProtocol",
    "Prerequisite",
    "PrerequisiteKind",
    "PrerequisiteStatus",
    "ProtocolConstraint",
    "ProtocolDataset",
    "ProtocolRiskManager",
    "ProtocolStrategy",
    "ResearchObjective",
    "ResearchObjectiveStatus",
    "RetryDisposition",
    "RobustnessRequirement",
    "TunableDimension",
    "TunableValueType",
    "WorkflowPlan",
    "WorkflowOutcome",
    "WorkflowOutcomeStatus",
    "WorkflowPlanStatus",
    "WorkflowStep",
    "WorkflowStepResult",
    "WorkflowStepStatus",
    "RESEARCH_RECORD_WORKFLOW_OUTCOME",
    "RESEARCH_REGISTER_EXPERIMENT_WORKFLOW",
    "record_workflow_outcome",
    "register_experiment_workflow",
]
