"""Declare research artifact types and their bounded-context owners.

The mappings are the authoritative vocabulary used by persistence, handoffs,
and orchestration validation. Adding or reassigning a type changes governance
and must stay synchronized with canonical writers and active documentation.
"""

from __future__ import annotations

from trader_research.foundation import (
    DATA_DOMAIN_OWNER,
    EXPERIMENTS_DOMAIN_OWNER,
    KNOWLEDGE_METHODOLOGY_DOMAIN_OWNER,
    ML_DOMAIN_OWNER,
    ORCHESTRATION_DOMAIN_OWNER,
    REVIEW_DOMAIN_OWNER,
)


DATA_AGENT_OWNER = "Data Agent"
QUANT_RESEARCH_SUPERVISOR_OWNER = "Quant Research Supervisor Agent"
QUANTITATIVE_METHODS_OWNER = "Quantitative Methods Agent"
MATH_CODER_OWNER = QUANTITATIVE_METHODS_OWNER
ML_AGENT_OWNER = "ML Agent"
HYPOTHESIS_AGENT_OWNER = "Hypothesis Agent"
EVALUATION_AGENT_OWNER = "Evaluation Agent"
ADVERSARIAL_AGENT_OWNER = "Adversarial Agent"

DATASET_MANIFEST = "dataset_manifest"
DATA_QUALITY_REPORT = "data_quality_report"
HYPOTHESIS_CARD = "hypothesis_card"
KNOWLEDGE_SOURCE_MANIFEST = "knowledge_source_manifest"
KNOWLEDGE_INGESTION_REPORT = "knowledge_ingestion_report"
KNOWLEDGE_CHUNK_MANIFEST = "knowledge_chunk_manifest"
KNOWLEDGE_EMBEDDING_MANIFEST = "knowledge_embedding_manifest"
METHODOLOGY_CANDIDATE = "methodology_candidate"
METHODOLOGY_EVIDENCE_PACKET = "methodology_evidence_packet"
METHODOLOGY_FIELD_EXTRACTION_REPORT = "methodology_field_extraction_report"
METHODOLOGY_CANDIDATE_VALIDATION_REPORT = "methodology_candidate_validation_report"
METHOD_CARD_DRAFT = "method_card_draft"
METHOD_CARD = "method_card"
METHOD_IMPLEMENTATION_MANIFEST = "method_implementation_manifest"
METHOD_PACKAGE_MANIFEST = "method_package_manifest"
INDICATOR_VALIDATION_REPORT = "indicator_validation_report"
SIGNAL_IMPLEMENTATION_VALIDATION_REPORT = "signal_implementation_validation_report"
SIGNAL_DIAGNOSTIC_REPORT = "signal_diagnostic_report"
MULTIPLE_TESTING_REPORT = "multiple_testing_report"
CXX_KERNEL_MANIFEST = "cxx_kernel_manifest"
EVIDENCE_RETRIEVAL_REPORT = "evidence_retrieval_report"
CITATION_VALIDATION_REPORT = "citation_validation_report"
INDICATOR_METADATA = "indicator_metadata"
STATISTICAL_TEST_REPORT = "statistical_test_report"
FEATURE_MANIFEST = "feature_dataset_manifest"
MODEL_CARD = "model_card"
PREDICTION_ARTIFACT = "prediction_artifact"
DRIFT_REPORT = "drift_report"
ML_FEATURE_SET_SPEC = "ml_feature_set_spec"
ML_FEATURE_SET_VALIDATION_REPORT = "ml_feature_set_validation_report"
ML_MODEL_VERSION_REF = "ml_model_version_ref"
ML_DEPLOYMENT_MANIFEST = "ml_deployment_manifest"
ML_DEPLOYMENT_VALIDATION_REPORT = "ml_deployment_validation_report"
RESEARCH_OBJECTIVE = "research_objective"
EXPERIMENT_PROTOCOL = "experiment_protocol"
WORKFLOW_PLAN = "workflow_plan"
APPROVAL_REQUEST = "approval_request"
WORKFLOW_OUTCOME = "workflow_outcome"
EXPERIMENT_PLAN = "experiment_plan"
IMPLEMENTATION_VERSION = "implementation_version"
IMPLEMENTATION_VALIDATION_REPORT = "implementation_validation_report"
STRATEGY_SPECIFICATION = "strategy_specification"
STRATEGY_SPECIFICATION_VALIDATION_REPORT = "strategy_specification_validation_report"
RISK_STACK_SPECIFICATION = "risk_stack_specification"
RISK_STACK_SPECIFICATION_VALIDATION_REPORT = "risk_stack_specification_validation_report"
BACKTEST_SPECIFICATION = "backtest_specification"
BACKTEST_SPECIFICATION_VALIDATION_REPORT = "backtest_specification_validation_report"
BACKTEST_RUN = "backtest_run"
PARAMETER_OPTIMIZATION_PLAN = "parameter_optimization_plan"
PARAMETER_OPTIMIZATION_RUN = "parameter_optimization_run"
PARAMETER_OPTIMIZATION_TRIAL = "parameter_optimization_trial"
EXPERIMENT_TRACKING_PROJECTION_REPORT = "experiment_tracking_projection_report"
PARAMETER_OPTIMIZATION_EVALUATION_REPORT = "parameter_optimization_evaluation_report"
PARAMETER_OPTIMIZATION_AUDIT_PLAN = "parameter_optimization_audit_plan"
PARAMETER_OPTIMIZATION_ROBUSTNESS_REPORT = "parameter_optimization_robustness_report"
COMPARISON_REPORT = "comparison_report"
EVALUATION_REPORT = "evaluation_report"
ROBUSTNESS_REPORT = "robustness_report"
RECOMMENDATION_REPORT = "recommendation_report"
RESEARCH_VERDICT = "research_verdict"

DOMAIN_OWNER_BY_ARTIFACT_TYPE = {
    DATASET_MANIFEST: DATA_DOMAIN_OWNER,
    DATA_QUALITY_REPORT: DATA_DOMAIN_OWNER,
    HYPOTHESIS_CARD: EXPERIMENTS_DOMAIN_OWNER,
    KNOWLEDGE_SOURCE_MANIFEST: KNOWLEDGE_METHODOLOGY_DOMAIN_OWNER,
    KNOWLEDGE_INGESTION_REPORT: KNOWLEDGE_METHODOLOGY_DOMAIN_OWNER,
    KNOWLEDGE_CHUNK_MANIFEST: KNOWLEDGE_METHODOLOGY_DOMAIN_OWNER,
    KNOWLEDGE_EMBEDDING_MANIFEST: KNOWLEDGE_METHODOLOGY_DOMAIN_OWNER,
    METHODOLOGY_CANDIDATE: KNOWLEDGE_METHODOLOGY_DOMAIN_OWNER,
    METHODOLOGY_EVIDENCE_PACKET: KNOWLEDGE_METHODOLOGY_DOMAIN_OWNER,
    METHODOLOGY_FIELD_EXTRACTION_REPORT: KNOWLEDGE_METHODOLOGY_DOMAIN_OWNER,
    METHODOLOGY_CANDIDATE_VALIDATION_REPORT: KNOWLEDGE_METHODOLOGY_DOMAIN_OWNER,
    METHOD_CARD_DRAFT: KNOWLEDGE_METHODOLOGY_DOMAIN_OWNER,
    METHOD_CARD: KNOWLEDGE_METHODOLOGY_DOMAIN_OWNER,
    METHOD_IMPLEMENTATION_MANIFEST: KNOWLEDGE_METHODOLOGY_DOMAIN_OWNER,
    METHOD_PACKAGE_MANIFEST: KNOWLEDGE_METHODOLOGY_DOMAIN_OWNER,
    INDICATOR_VALIDATION_REPORT: KNOWLEDGE_METHODOLOGY_DOMAIN_OWNER,
    SIGNAL_IMPLEMENTATION_VALIDATION_REPORT: KNOWLEDGE_METHODOLOGY_DOMAIN_OWNER,
    SIGNAL_DIAGNOSTIC_REPORT: KNOWLEDGE_METHODOLOGY_DOMAIN_OWNER,
    MULTIPLE_TESTING_REPORT: KNOWLEDGE_METHODOLOGY_DOMAIN_OWNER,
    CXX_KERNEL_MANIFEST: KNOWLEDGE_METHODOLOGY_DOMAIN_OWNER,
    EVIDENCE_RETRIEVAL_REPORT: KNOWLEDGE_METHODOLOGY_DOMAIN_OWNER,
    CITATION_VALIDATION_REPORT: KNOWLEDGE_METHODOLOGY_DOMAIN_OWNER,
    INDICATOR_METADATA: KNOWLEDGE_METHODOLOGY_DOMAIN_OWNER,
    STATISTICAL_TEST_REPORT: KNOWLEDGE_METHODOLOGY_DOMAIN_OWNER,
    FEATURE_MANIFEST: ML_DOMAIN_OWNER,
    MODEL_CARD: ML_DOMAIN_OWNER,
    PREDICTION_ARTIFACT: ML_DOMAIN_OWNER,
    DRIFT_REPORT: ML_DOMAIN_OWNER,
    ML_FEATURE_SET_SPEC: ML_DOMAIN_OWNER,
    ML_FEATURE_SET_VALIDATION_REPORT: ML_DOMAIN_OWNER,
    ML_MODEL_VERSION_REF: ML_DOMAIN_OWNER,
    ML_DEPLOYMENT_MANIFEST: ML_DOMAIN_OWNER,
    ML_DEPLOYMENT_VALIDATION_REPORT: ML_DOMAIN_OWNER,
    RESEARCH_OBJECTIVE: ORCHESTRATION_DOMAIN_OWNER,
    EXPERIMENT_PROTOCOL: EXPERIMENTS_DOMAIN_OWNER,
    WORKFLOW_PLAN: ORCHESTRATION_DOMAIN_OWNER,
    APPROVAL_REQUEST: ORCHESTRATION_DOMAIN_OWNER,
    WORKFLOW_OUTCOME: ORCHESTRATION_DOMAIN_OWNER,
    EXPERIMENT_PLAN: ORCHESTRATION_DOMAIN_OWNER,
    IMPLEMENTATION_VERSION: EXPERIMENTS_DOMAIN_OWNER,
    IMPLEMENTATION_VALIDATION_REPORT: EXPERIMENTS_DOMAIN_OWNER,
    STRATEGY_SPECIFICATION: EXPERIMENTS_DOMAIN_OWNER,
    STRATEGY_SPECIFICATION_VALIDATION_REPORT: EXPERIMENTS_DOMAIN_OWNER,
    RISK_STACK_SPECIFICATION: EXPERIMENTS_DOMAIN_OWNER,
    RISK_STACK_SPECIFICATION_VALIDATION_REPORT: EXPERIMENTS_DOMAIN_OWNER,
    BACKTEST_SPECIFICATION: EXPERIMENTS_DOMAIN_OWNER,
    BACKTEST_SPECIFICATION_VALIDATION_REPORT: EXPERIMENTS_DOMAIN_OWNER,
    BACKTEST_RUN: EXPERIMENTS_DOMAIN_OWNER,
    PARAMETER_OPTIMIZATION_PLAN: EXPERIMENTS_DOMAIN_OWNER,
    PARAMETER_OPTIMIZATION_RUN: EXPERIMENTS_DOMAIN_OWNER,
    PARAMETER_OPTIMIZATION_TRIAL: EXPERIMENTS_DOMAIN_OWNER,
    EXPERIMENT_TRACKING_PROJECTION_REPORT: EXPERIMENTS_DOMAIN_OWNER,
    PARAMETER_OPTIMIZATION_EVALUATION_REPORT: REVIEW_DOMAIN_OWNER,
    PARAMETER_OPTIMIZATION_AUDIT_PLAN: REVIEW_DOMAIN_OWNER,
    PARAMETER_OPTIMIZATION_ROBUSTNESS_REPORT: REVIEW_DOMAIN_OWNER,
    COMPARISON_REPORT: EXPERIMENTS_DOMAIN_OWNER,
    EVALUATION_REPORT: REVIEW_DOMAIN_OWNER,
    ROBUSTNESS_REPORT: REVIEW_DOMAIN_OWNER,
    RECOMMENDATION_REPORT: REVIEW_DOMAIN_OWNER,
    RESEARCH_VERDICT: REVIEW_DOMAIN_OWNER,
}

SUPPORTED_ARTIFACT_TYPES = frozenset(DOMAIN_OWNER_BY_ARTIFACT_TYPE)
